#ifndef TOP_LEVEL_STD
#define TOP_LEVEL_ONEAPI_TBB_BLOCKED_RANGE2D_H
#define TOP_LEVEL_STD
#endif // TOP_LEVEL_STD

#include_next <oneapi/tbb/blocked_range2d.h>

#ifdef TOP_LEVEL_ONEAPI_TBB_BLOCKED_RANGE2D_H
#undef TOP_LEVEL_ONEAPI_TBB_BLOCKED_RANGE2D_H
#undef TOP_LEVEL_STD

#endif // TOP_LEVEL_ONEAPI_TBB_BLOCKED_RANGE2D_H
