#ifndef TOP_LEVEL_STD
#define TOP_LEVEL_ONEAPI_TBB_BLOCKED_RANGEND_H
#define TOP_LEVEL_STD
#endif // TOP_LEVEL_STD

#include_next <oneapi/tbb/blocked_rangeNd.h>

#ifdef TOP_LEVEL_ONEAPI_TBB_BLOCKED_RANGEND_H
#undef TOP_LEVEL_ONEAPI_TBB_BLOCKED_RANGEND_H
#undef TOP_LEVEL_STD

#endif // TOP_LEVEL_ONEAPI_TBB_BLOCKED_RANGEND_H
