#ifndef TOP_LEVEL_STD
#define TOP_LEVEL_ONEAPI_TBB_COLLABORATIVE_CALL_ONCE_H
#define TOP_LEVEL_STD
#endif // TOP_LEVEL_STD

#include_next <oneapi/tbb/collaborative_call_once.h>

#ifdef TOP_LEVEL_ONEAPI_TBB_COLLABORATIVE_CALL_ONCE_H
#undef TOP_LEVEL_ONEAPI_TBB_COLLABORATIVE_CALL_ONCE_H
#undef TOP_LEVEL_STD

#endif // TOP_LEVEL_ONEAPI_TBB_COLLABORATIVE_CALL_ONCE_H
