#ifndef TOP_LEVEL_STD
#define TOP_LEVEL_ONEAPI_TBB_COMBINABLE_H
#define TOP_LEVEL_STD
#endif // TOP_LEVEL_STD

#include_next <oneapi/tbb/combinable.h>

#ifdef TOP_LEVEL_ONEAPI_TBB_COMBINABLE_H
#undef TOP_LEVEL_ONEAPI_TBB_COMBINABLE_H
#undef TOP_LEVEL_STD

#endif // TOP_LEVEL_ONEAPI_TBB_COMBINABLE_H
