#ifndef TOP_LEVEL_STD
#define TOP_LEVEL_ONEAPI_TBB_CONCURRENT_SET_H
#define TOP_LEVEL_STD
#endif // TOP_LEVEL_STD

#include_next <oneapi/tbb/concurrent_set.h>

#ifdef TOP_LEVEL_ONEAPI_TBB_CONCURRENT_SET_H
#undef TOP_LEVEL_ONEAPI_TBB_CONCURRENT_SET_H
#undef TOP_LEVEL_STD

#endif // TOP_LEVEL_ONEAPI_TBB_CONCURRENT_SET_H
