#ifndef TOP_LEVEL_STD
#define TOP_LEVEL_ONEAPI_TBB_CONCURRENT_MAP_H
#define TOP_LEVEL_STD
#endif // TOP_LEVEL_STD

#include_next <oneapi/tbb/concurrent_map.h>

#ifdef TOP_LEVEL_ONEAPI_TBB_CONCURRENT_MAP_H
#undef TOP_LEVEL_ONEAPI_TBB_CONCURRENT_MAP_H
#undef TOP_LEVEL_STD

#endif // TOP_LEVEL_ONEAPI_TBB_CONCURRENT_MAP_H
