#ifndef TOP_LEVEL_STD
#define TOP_LEVEL_ONEAPI_TBB_ENUMERABLE_THREAD_SPECIFIC_H
#define TOP_LEVEL_STD
#endif // TOP_LEVEL_STD

#include_next <oneapi/tbb/enumerable_thread_specific.h>

#ifdef TOP_LEVEL_ONEAPI_TBB_ENUMERABLE_THREAD_SPECIFIC_H
#undef TOP_LEVEL_ONEAPI_TBB_ENUMERABLE_THREAD_SPECIFIC_H
#undef TOP_LEVEL_STD

#endif // TOP_LEVEL_ONEAPI_TBB_ENUMERABLE_THREAD_SPECIFIC_H
