#ifndef TOP_LEVEL_STD
#define TOP_LEVEL_ONEAPI_TBB_FLOW_GRAPH_ABSTRACTIONS_H
#define TOP_LEVEL_STD
#endif // TOP_LEVEL_STD

#include_next <oneapi/tbb/flow_graph_abstractions.h>

#ifdef TOP_LEVEL_ONEAPI_TBB_FLOW_GRAPH_ABSTRACTIONS_H
#undef TOP_LEVEL_ONEAPI_TBB_FLOW_GRAPH_ABSTRACTIONS_H
#undef TOP_LEVEL_STD

#endif // TOP_LEVEL_ONEAPI_TBB_FLOW_GRAPH_ABSTRACTIONS_H
