#ifndef TOP_LEVEL_STD
#define TOP_LEVEL_ONEAPI_TBB_GLOBAL_CONTROL_H
#define TOP_LEVEL_STD
#endif // TOP_LEVEL_STD

#include_next <oneapi/tbb/global_control.h>

#ifdef TOP_LEVEL_ONEAPI_TBB_GLOBAL_CONTROL_H
#undef TOP_LEVEL_ONEAPI_TBB_GLOBAL_CONTROL_H
#undef TOP_LEVEL_STD

#endif // TOP_LEVEL_ONEAPI_TBB_GLOBAL_CONTROL_H
