#ifndef TOP_LEVEL_STD
#define TOP_LEVEL_ONEAPI_TBB_NULL_RW_MUTEX_H
#define TOP_LEVEL_STD
#endif // TOP_LEVEL_STD

#include_next <oneapi/tbb/null_rw_mutex.h>

#ifdef TOP_LEVEL_ONEAPI_TBB_NULL_RW_MUTEX_H
#undef TOP_LEVEL_ONEAPI_TBB_NULL_RW_MUTEX_H
#undef TOP_LEVEL_STD

#endif // TOP_LEVEL_ONEAPI_TBB_NULL_RW_MUTEX_H
