#ifndef TOP_LEVEL_STD
#define TOP_LEVEL_ONEAPI_TBB_PARALLEL_SORT_H
#define TOP_LEVEL_STD
#endif // TOP_LEVEL_STD

#include_next <oneapi/tbb/parallel_sort.h>

#ifdef TOP_LEVEL_ONEAPI_TBB_PARALLEL_SORT_H
#undef TOP_LEVEL_ONEAPI_TBB_PARALLEL_SORT_H
#undef TOP_LEVEL_STD

#endif // TOP_LEVEL_ONEAPI_TBB_PARALLEL_SORT_H
