#ifndef TOP_LEVEL_STD
#define TOP_LEVEL_ONEAPI_TBB_PARTITIONER_H
#define TOP_LEVEL_STD
#endif // TOP_LEVEL_STD

#include_next <oneapi/tbb/partitioner.h>

#ifdef TOP_LEVEL_ONEAPI_TBB_PARTITIONER_H
#undef TOP_LEVEL_ONEAPI_TBB_PARTITIONER_H
#undef TOP_LEVEL_STD

#endif // TOP_LEVEL_ONEAPI_TBB_PARTITIONER_H
