#ifndef TOP_LEVEL_STD
#define TOP_LEVEL_ONEAPI_TBB_SCALABLE_ALLOCATOR_H
#define TOP_LEVEL_STD
#endif // TOP_LEVEL_STD

#include_next <oneapi/tbb/scalable_allocator.h>

#ifdef TOP_LEVEL_ONEAPI_TBB_SCALABLE_ALLOCATOR_H
#undef TOP_LEVEL_ONEAPI_TBB_SCALABLE_ALLOCATOR_H
#undef TOP_LEVEL_STD

#endif // TOP_LEVEL_ONEAPI_TBB_SCALABLE_ALLOCATOR_H
