#ifndef TOP_LEVEL_STD
#define TOP_LEVEL_ONEAPI_TBB_TASK_GROUP_H
#define TOP_LEVEL_STD
#endif // TOP_LEVEL_STD

#include_next <oneapi/tbb/task_group.h>

#ifdef TOP_LEVEL_ONEAPI_TBB_TASK_GROUP_H
#undef TOP_LEVEL_ONEAPI_TBB_TASK_GROUP_H
#undef TOP_LEVEL_STD

#endif // TOP_LEVEL_ONEAPI_TBB_TASK_GROUP_H
