#ifndef TOP_LEVEL_STD
#define TOP_LEVEL_ONEAPI_TBB_TASK_SCHEDULER_OBSERVER_H
#define TOP_LEVEL_STD
#endif // TOP_LEVEL_STD

#include_next <oneapi/tbb/task_scheduler_observer.h>

#ifdef TOP_LEVEL_ONEAPI_TBB_TASK_SCHEDULER_OBSERVER_H
#undef TOP_LEVEL_ONEAPI_TBB_TASK_SCHEDULER_OBSERVER_H
#undef TOP_LEVEL_STD

#endif // TOP_LEVEL_ONEAPI_TBB_TASK_SCHEDULER_OBSERVER_H
