#ifndef TOP_LEVEL_STD
#define TOP_LEVEL_ONEAPI_TBB_TBBMALLOC_PROXY_H
#define TOP_LEVEL_STD
#endif // TOP_LEVEL_STD

#include_next <oneapi/tbb/tbbmalloc_proxy.h>

#ifdef TOP_LEVEL_ONEAPI_TBB_TBBMALLOC_PROXY_H
#undef TOP_LEVEL_ONEAPI_TBB_TBBMALLOC_PROXY_H
#undef TOP_LEVEL_STD

#endif // TOP_LEVEL_ONEAPI_TBB_TBBMALLOC_PROXY_H
